version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antibinance_web
    ports:
      - "3001:3000" # Map to 3001 since 3000 is occupied by crypto-frontend!
    environment:
      - DATABASE_URL
      - JWT_SECRET
    restart: always
    command: sh -c "npx drizzle-kit push && npm run start"
